apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-service
  namespace: {{ $.Values.app.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $service.port | default 8000 }}
{{- end }}