name: Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          token: ${{ secrets.HELM_TOKEN }}

      - name: Package the Helm charts
        run: |
          helm package gochart -d ./docs

      - name: Create or update index.yaml
        run: helm repo index ./docs --url https://Gad-Ongoro.github.io/helm-charts/

      - name: Configure Git for GitHub Actions bot
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add SSH key for GitHub Actions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Commit and push to gh-pages
        run: |
          git fetch origin
          git checkout gh-pages || git checkout -b gh-pages
          cp -r ./docs/* .
          git add .
          git commit -m "Update Helm chart repository index" || echo "No changes to commit"
          git push origin gh-pages
